// ─── Gemini API (proxied — key stays server-side) ─────────────────────────────
export async function callGemini(prompt, maxTokens = 1000) {
  const res = await fetch("/api/gemini", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { maxOutputTokens: maxTokens, temperature: 0.7 },
    }),
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error.message || data.error);
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "No response.";
}

// ─── PDF Export ───────────────────────────────────────────────────────────────
export function exportWeekPDF({ weekKey, log, doneTasks, weekSummary }) {
  const weekNum = weekKey.replace("W", "");
  const weekDays = Object.entries(log)
    .filter(([k]) => k.startsWith(weekKey))
    .sort(([a], [b]) => a.localeCompare(b));
  const doneList = doneTasks.map((t) => `• ${t.title} (${t.type})`).join("\n");
  const dayRows = weekDays
    .map(([key, entry]) => {
      const d = key.split("-D")[1];
      const sp = entry.standup?.split("|||");
      return `
    <div class="day-block">
      <div class="day-title">Day ${d} <span class="day-date">${entry.date || ""}</span></div>
      ${entry.notes ? `<div class="day-notes"><strong>Notes:</strong><br/>${entry.notes.replace(/\n/g, "<br/>")}</div>` : ""}
      ${entry.summary ? `<div class="day-summary"><strong>AI Summary:</strong><br/>${entry.summary.replace(/\n/g, "<br/>")}</div>` : ""}
      ${sp ? `<div class="day-standup"><strong>Standup:</strong><br/>
        <em>✅ Did:</em> ${(sp[0] || "").replace(/\n/g, "<br/>")}<br/>
        <em>🔄 Today:</em> ${(sp[1] || "").replace(/\n/g, "<br/>")}<br/>
        <em>🚧 Blockers:</em> ${(sp[2] || "").replace(/\n/g, "<br/>")}
      </div>` : ""}
    </div>`;
    })
    .join("");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>QE Report — Week ${weekNum}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Sora:wght@400;600&display=swap');
  body{font-family:'IBM Plex Mono',monospace;color:#1e293b;max-width:820px;margin:0 auto;padding:40px 32px;background:#fff}
  h1{font-family:'Sora',sans-serif;font-size:24px;color:#0f172a;margin-bottom:4px}
  .subtitle{font-size:11px;color:#94a3b8;letter-spacing:.08em;text-transform:uppercase;margin-bottom:32px}
  .section-title{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#6366f1;margin:24px 0 10px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
  .day-block{margin-bottom:18px;padding:14px 16px;background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0}
  .day-title{font-family:'Sora',sans-serif;font-size:13px;font-weight:600;color:#0f172a;margin-bottom:8px}
  .day-date{font-size:11px;color:#94a3b8;font-weight:400;margin-left:8px}
  .day-notes,.day-summary,.day-standup{font-size:11px;line-height:1.7;color:#334155;margin-top:8px}
  .day-summary{background:#f0fdf4;padding:8px 10px;border-radius:4px;border-left:3px solid #22c55e}
  .day-standup{background:#eef2ff;padding:8px 10px;border-radius:4px;border-left:3px solid #6366f1}
  .done-list{font-size:11px;line-height:1.9;color:#334155;white-space:pre-wrap}
  .week-summary{font-size:11px;line-height:1.8;color:#334155;white-space:pre-wrap;background:#f0fdf4;padding:14px 16px;border-radius:8px;border:1px solid #bbf7d0}
  .footer{margin-top:40px;font-size:10px;color:#cbd5e1;text-align:center;border-top:1px solid #f1f5f9;padding-top:16px}
  @media print{body{padding:20px}}
</style></head><body>
  <h1>QE Intern Weekly Report</h1>
  <div class="subtitle">Week ${weekNum} &nbsp;·&nbsp; ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
  <div class="section-title">✓ Completed Tasks</div>
  <div class="done-list">${doneList || "No completed tasks recorded."}</div>
  <div class="section-title">📓 Daily Logs</div>
  ${dayRows || "<p style='color:#94a3b8;font-size:11px'>No daily logs recorded.</p>"}
  ${weekSummary ? `<div class="section-title">✦ AI Week Summary</div><div class="week-summary">${weekSummary.replace(/\n/g, "<br/>")}</div>` : ""}
  <div class="footer">Generated by QE Personal Board · Week ${weekNum}</div>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (win) win.onload = () => { win.focus(); win.print(); };
}

// ─── Practicum Report DOCX Generator ─────────────────────────────────────────
export async function generatePracticumDocx({ meta, sections }) {
  if (!window.docx) {
    await new Promise((res, rej) => {
      const s = document.createElement("script");
      s.src = "https://cdnjs.cloudflare.com/ajax/libs/docx/8.5.0/docx.umd.min.js";
      s.onload = res;
      s.onerror = rej;
      document.head.appendChild(s);
    });
  }
  const {
    Document, Packer, Paragraph, TextRun, AlignmentType,
    BorderStyle, WidthType, ShadingType, Table, TableRow, TableCell,
    PageOrientation, UnderlineType,
  } = window.docx;

  const PAGE = { width: 11906, height: 16838 };
  const MARGIN = { top: 1440, right: 1440, bottom: 1440, left: 1440 };
  const CONTENT_W = PAGE.width - MARGIN.left - MARGIN.right;

  const bdr = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
  const borders = { top: bdr, bottom: bdr, left: bdr, right: bdr };

  const infoRow = (label, value) =>
    new TableRow({
      children: [
        new TableCell({
          width: { size: 2700, type: WidthType.DXA }, borders,
          shading: { fill: "EEF2FF", type: ShadingType.CLEAR },
          margins: { top: 80, bottom: 80, left: 160, right: 80 },
          children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, font: "Arial", size: 22 })] })],
        }),
        new TableCell({
          width: { size: CONTENT_W - 2700, type: WidthType.DXA }, borders,
          margins: { top: 80, bottom: 80, left: 160, right: 80 },
          children: [new Paragraph({ children: [new TextRun({ text: value || "", font: "Arial", size: 22 })] })],
        }),
      ],
    });

  const sectionHeading = (roman, title) =>
    new Paragraph({
      spacing: { before: 320, after: 120 },
      children: [new TextRun({ text: `${roman}. ${title}`, bold: true, underline: { type: UnderlineType.SINGLE }, font: "Arial", size: 24 })],
    });

  const bodyParagraphs = (text) => {
    if (!text) return [new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: "N/A", font: "Arial", size: 22 })] })];
    return text.split("\n").filter((l) => l.trim() !== "").map((line) => {
      const isBullet = line.trim().startsWith("•") || line.trim().startsWith("-");
      const displayLine = isBullet && line.trim().startsWith("-") ? "• " + line.trim().slice(1).trim() : line.trim();
      return new Paragraph({
        spacing: { after: 100, line: 360, lineRule: "auto" },
        indent: isBullet ? { left: 720, hanging: 360 } : {},
        children: [new TextRun({ text: displayLine, font: "Arial", size: 22 })],
      });
    });
  };

  const spacer = (before = 0, after = 120) =>
    new Paragraph({ spacing: { before, after }, children: [new TextRun({ text: "", font: "Arial", size: 22 })] });

  const doc = new Document({
    styles: { default: { document: { run: { font: "Arial", size: 22 } } } },
    sections: [{
      properties: {
        page: { size: { width: PAGE.width, height: PAGE.height }, margin: MARGIN, orientation: PageOrientation.PORTRAIT },
      },
      children: [
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "WEEKLY PRACTICUM PROGRESS REPORT", bold: true, font: "Arial", size: 28 })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 280 }, children: [new TextRun({ text: "College of Information Technology", font: "Arial", size: 22, color: "444444" })] }),
        new Table({
          width: { size: CONTENT_W, type: WidthType.DXA },
          columnWidths: [2700, CONTENT_W - 2700],
          rows: [
            infoRow("Name:", meta.name),
            infoRow("Course & Section:", meta.course),
            infoRow("Practicum Week:", meta.practWeek),
            infoRow("Company/Office:", meta.company),
            infoRow("Position:", meta.position),
          ],
        }),
        spacer(240, 60),
        sectionHeading("I", "Tasks and Activities Performed"), ...bodyParagraphs(sections.tasks), spacer(60, 60),
        sectionHeading("II", "Learning Outcomes and Skills Gained"), ...bodyParagraphs(sections.learning), spacer(60, 60),
        sectionHeading("III", "Challenges Encountered"), ...bodyParagraphs(sections.challenges), spacer(60, 60),
        sectionHeading("IV", "Supervisor's Remarks / Feedback"), ...bodyParagraphs(sections.supervisor), spacer(60, 60),
        sectionHeading("V", "Proof of Work / Engagement"),
        new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: "(Attach screenshots, photos of tasks, attendance records, or other outputs below.)", font: "Arial", size: 22, italics: true, color: "888888" })] }),
      ],
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const lastName = (meta.name || "Intern").trim().split(/\s+/).pop();
  const weekLabel = `Week${meta.practWeek.match(/\d+/)?.[0] || "1"}`;
  const sectionClean = (meta.course || "BSIT4A").replace(/\s+/g, "");
  a.download = `${sectionClean}_${weekLabel}_${lastName}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
